//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ExpenseTrackerModel", "FK_BudgetItem_0", "Budget", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExpenseTracker.Framework.Models.Budget), "BudgetItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseTracker.Framework.Models.BudgetItem), true)]

#endregion

namespace ExpenseTracker.Framework.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpenseTrackerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpenseTrackerEntities object using the connection string found in the 'ExpenseTrackerEntities' section of the application configuration file.
        /// </summary>
        public ExpenseTrackerEntities() : base("name=ExpenseTrackerEntities", "ExpenseTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseTrackerEntities object.
        /// </summary>
        public ExpenseTrackerEntities(string connectionString) : base(connectionString, "ExpenseTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseTrackerEntities object.
        /// </summary>
        public ExpenseTrackerEntities(EntityConnection connection) : base(connection, "ExpenseTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Budget> Budgets
        {
            get
            {
                if ((_Budgets == null))
                {
                    _Budgets = base.CreateObjectSet<Budget>("Budgets");
                }
                return _Budgets;
            }
        }
        private ObjectSet<Budget> _Budgets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BudgetItem> BudgetItems
        {
            get
            {
                if ((_BudgetItems == null))
                {
                    _BudgetItems = base.CreateObjectSet<BudgetItem>("BudgetItems");
                }
                return _BudgetItems;
            }
        }
        private ObjectSet<BudgetItem> _BudgetItems;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Budgets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBudgets(Budget budget)
        {
            base.AddObject("Budgets", budget);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BudgetItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBudgetItems(BudgetItem budgetItem)
        {
            base.AddObject("BudgetItems", budgetItem);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseTrackerModel", Name="Budget")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Budget : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Budget object.
        /// </summary>
        /// <param name="budgetId">Initial value of the BudgetId property.</param>
        /// <param name="budgetDate">Initial value of the BudgetDate property.</param>
        /// <param name="budgetAmount">Initial value of the BudgetAmount property.</param>
        public static Budget CreateBudget(global::System.Int32 budgetId, global::System.DateTime budgetDate, global::System.Decimal budgetAmount)
        {
            Budget budget = new Budget();
            budget.BudgetId = budgetId;
            budget.BudgetDate = budgetDate;
            budget.BudgetAmount = budgetAmount;
            return budget;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BudgetId
        {
            get
            {
                return _BudgetId;
            }
            set
            {
                if (_BudgetId != value)
                {
                    OnBudgetIdChanging(value);
                    ReportPropertyChanging("BudgetId");
                    _BudgetId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BudgetId");
                    OnBudgetIdChanged();
                }
            }
        }
        private global::System.Int32 _BudgetId;
        partial void OnBudgetIdChanging(global::System.Int32 value);
        partial void OnBudgetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BudgetDate
        {
            get
            {
                return _BudgetDate;
            }
            set
            {
                OnBudgetDateChanging(value);
                ReportPropertyChanging("BudgetDate");
                _BudgetDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BudgetDate");
                OnBudgetDateChanged();
            }
        }
        private global::System.DateTime _BudgetDate;
        partial void OnBudgetDateChanging(global::System.DateTime value);
        partial void OnBudgetDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BudgetAmount
        {
            get
            {
                return _BudgetAmount;
            }
            set
            {
                OnBudgetAmountChanging(value);
                ReportPropertyChanging("BudgetAmount");
                _BudgetAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BudgetAmount");
                OnBudgetAmountChanged();
            }
        }
        private global::System.Decimal _BudgetAmount;
        partial void OnBudgetAmountChanging(global::System.Decimal value);
        partial void OnBudgetAmountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseTrackerModel", "FK_BudgetItem_0", "BudgetItem")]
        public EntityCollection<BudgetItem> BudgetItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BudgetItem>("ExpenseTrackerModel.FK_BudgetItem_0", "BudgetItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BudgetItem>("ExpenseTrackerModel.FK_BudgetItem_0", "BudgetItem", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseTrackerModel", Name="BudgetItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BudgetItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BudgetItem object.
        /// </summary>
        /// <param name="budgetItemId">Initial value of the BudgetItemId property.</param>
        /// <param name="budgetId">Initial value of the BudgetId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="isPaid">Initial value of the IsPaid property.</param>
        /// <param name="datePaid">Initial value of the DatePaid property.</param>
        /// <param name="dueDate">Initial value of the DueDate property.</param>
        public static BudgetItem CreateBudgetItem(global::System.Int32 budgetItemId, global::System.Int32 budgetId, global::System.String description, global::System.Decimal amount, global::System.Boolean isPaid, global::System.DateTime datePaid, global::System.DateTime dueDate)
        {
            BudgetItem budgetItem = new BudgetItem();
            budgetItem.BudgetItemId = budgetItemId;
            budgetItem.BudgetId = budgetId;
            budgetItem.Description = description;
            budgetItem.Amount = amount;
            budgetItem.IsPaid = isPaid;
            budgetItem.DatePaid = datePaid;
            budgetItem.DueDate = dueDate;
            return budgetItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BudgetItemId
        {
            get
            {
                return _BudgetItemId;
            }
            set
            {
                if (_BudgetItemId != value)
                {
                    OnBudgetItemIdChanging(value);
                    ReportPropertyChanging("BudgetItemId");
                    _BudgetItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BudgetItemId");
                    OnBudgetItemIdChanged();
                }
            }
        }
        private global::System.Int32 _BudgetItemId;
        partial void OnBudgetItemIdChanging(global::System.Int32 value);
        partial void OnBudgetItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BudgetId
        {
            get
            {
                return _BudgetId;
            }
            set
            {
                OnBudgetIdChanging(value);
                ReportPropertyChanging("BudgetId");
                _BudgetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BudgetId");
                OnBudgetIdChanged();
            }
        }
        private global::System.Int32 _BudgetId;
        partial void OnBudgetIdChanging(global::System.Int32 value);
        partial void OnBudgetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPaid
        {
            get
            {
                return _IsPaid;
            }
            set
            {
                OnIsPaidChanging(value);
                ReportPropertyChanging("IsPaid");
                _IsPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPaid");
                OnIsPaidChanged();
            }
        }
        private global::System.Boolean _IsPaid;
        partial void OnIsPaidChanging(global::System.Boolean value);
        partial void OnIsPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DatePaid
        {
            get
            {
                return _DatePaid;
            }
            set
            {
                OnDatePaidChanging(value);
                ReportPropertyChanging("DatePaid");
                _DatePaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePaid");
                OnDatePaidChanged();
            }
        }
        private global::System.DateTime _DatePaid;
        partial void OnDatePaidChanging(global::System.DateTime value);
        partial void OnDatePaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseTrackerModel", "FK_BudgetItem_0", "Budget")]
        public Budget Budget
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Budget>("ExpenseTrackerModel.FK_BudgetItem_0", "Budget").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Budget>("ExpenseTrackerModel.FK_BudgetItem_0", "Budget").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Budget> BudgetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Budget>("ExpenseTrackerModel.FK_BudgetItem_0", "Budget");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Budget>("ExpenseTrackerModel.FK_BudgetItem_0", "Budget", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
