//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaycheckBudgetItem
    {
        public int PaycheckBudgetItemId { get; set; }
        public int PaycheckBudgetId { get; set; }
        public System.DateTime PaidDate { get; set; }
        public decimal Amount { get; set; }
        public bool IsPaid { get; set; }
        public string Description { get; set; }
    
        public virtual PaycheckBudget PaycheckBudget { get; set; }
    }
}
